"""
AetherGuardRAG — main SDK client.

This module is the primary entry point for the aetherguard-rag-security SDK.
It is a thin async REST client that delegates ALL security work to backend-api.

The client does NOT:
- Talk to any vector database
- Generate embeddings
- Run ML models
- Perform cryptographic operations (hashing, signing, verification)
- Access PostgreSQL or immudb directly

All of the above are handled server-side by backend-api's /api/v1/rag/* endpoints.
"""
from __future__ import annotations

from typing import Any

from ._http import HTTPTransport
from .exceptions import (
    AetherGuardError,
    AuthorizationError,
    ConnectionError,  # noqa: F401 — re-exported for convenience
    IngestError,
    RetrievalDeniedError,
)
from .models import (
    AuthorizeResult,
    ChunkInput,
    ChunkMetadata,
    IngestResult,
    RetrieveResult,
    SafeChunk,
    VerifyResult,
)

__all__ = ["AetherGuardRAG"]


class AetherGuardRAG:
    """
    Lightweight async SDK client for AetherGuard RAG Pipeline Security.

    Usage — async context manager (recommended)::

        async with AetherGuardRAG(api_url="https://rag-secure.aetherguard.ai", api_key="...") as ag:
            result = await ag.secure_ingest(chunks, embeddings,region="us-east-1")

    Usage — explicit lifecycle::

        ag = AetherGuardRAG(api_url="https://rag-secure.aetherguard.ai", api_key="...")
        try:
            result = await ag.secure_ingest(...)
        finally:
            await ag.close()

    Parameters
    ----------
    api_url:
        Base URL of backend-api (e.g. ``"https://rag-secure.aetherguard.ai"``).
    api_key:
        API key used for Bearer-token authentication on every request.
    timeout:
        Per-request timeout in seconds (default 30).
    max_retries:
        Maximum retry attempts for transient failures — 502, 503, 504,
        and connection errors (default 3).  Retries use exponential backoff
        with delays of 1 s, 2 s, 4 s, …
    """

    def __init__(
        self,
        api_url: str,
        api_key: str,
        timeout: float = 30.0,
        max_retries: int = 3,
    ) -> None:
        self._transport = HTTPTransport(
            base_url=api_url,
            api_key=api_key,
            timeout=timeout,
            max_retries=max_retries,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def secure_ingest(
        self,
        chunks: list[str],
        embeddings: list[list[float]],
        region: str,
        document_id: str | None = None,
        source_type: str = "unknown",
        embedding_model_id: str | None = None,
        embedding_model_version: str | None = None,
    ) -> IngestResult:
        """
        Send chunks + embeddings to backend-api for security processing.

        Backend-api will hash, scan, sign, and store each chunk, then return
        per-chunk metadata that you store alongside your vectors in your
        vector database.

        Parameters
        ----------
        chunks:
            Text chunks already split by the customer.
        embeddings:
            Embedding vectors already generated by the customer.
            ``len(embeddings)`` must equal ``len(chunks)``.
        region:
            Data-residency region (``^[a-zA-Z0-9_-]+$``, max 64 chars).
        document_id:
            Optional source document identifier.
        source_type:
            Document source type (e.g. ``"confluence"``, ``"s3"``).
        embedding_model_id:
            Identifier of the model used to generate embeddings.
        embedding_model_version:
            Version of the embedding model.

        Returns
        -------
        IngestResult
            Per-chunk metadata (chunk_id, chunk_hash, signature, …).

        Raises
        ------
        ValueError
            If ``len(chunks) != len(embeddings)`` — validated locally before
            any network call is made.
        IngestError
            If backend-api returns an error response.
        ConnectionError
            If backend-api is unreachable after all retry attempts.
        """
        if len(chunks) != len(embeddings):
            raise ValueError(
                f"chunks and embeddings must have the same length, "
                f"got {len(chunks)} chunks and {len(embeddings)} embeddings"
            )

        payload: dict[str, Any] = {
            "chunks": [
                {
                    "content": chunk,
                    "embedding": embedding,
                    "position": idx,
                }
                for idx, (chunk, embedding) in enumerate(zip(chunks, embeddings))
            ],
            "region": region,
            "source_type": source_type,
        }
        if document_id is not None:
            payload["document_id"] = document_id
        if embedding_model_id is not None:
            payload["embedding_model_id"] = embedding_model_id
        if embedding_model_version is not None:
            payload["embedding_model_version"] = embedding_model_version

        response = await self._transport.post("/api/v1/rag/secure-ingest", json=payload)

        if response.status_code != 200:
            body = _safe_json(response)
            raise IngestError(
                f"secure_ingest failed with HTTP {response.status_code}",
                status_code=response.status_code,
                detail=body.get("detail") or body.get("error") or response.text,
            )

        data = response.json()
        return IngestResult(
            metadata=[_parse_chunk_metadata(m) for m in data["metadata"]],
            document_id=data["document_id"],
            total_chunks=data["total_chunks"],
            blocked_chunks=data["blocked_chunks"],
            evidence_id=data["evidence_id"],
        )

    async def secure_retrieve(
        self,
        raw_results: list[dict[str, Any]],
        email: str,
        region: str,
        max_tokens: int = 4096,
        trust_threshold: str = "trusted",
        max_injection_score: float = 0.7,
    ) -> RetrieveResult:
        """
        Send raw vector DB results to backend-api for verification and sanitisation.

        Backend-api will authorise the request, verify chunk hashes and KMS
        signatures, scan chunks, sanitise content, and assemble safe context
        within the requested token budget.

        Parameters
        ----------
        raw_results:
            Raw results from the customer's vector DB query.  Each dict must
            contain at minimum: ``chunk_id``, ``content``, ``metadata``.
        email:
            Requesting user's email address used for authorisation.
        region:
            Data-residency region.
        max_tokens:
            Maximum tokens in the assembled context (default 4096).
        trust_threshold:
            Minimum trust level to include in context
            (``"verified"``, ``"trusted"``, or ``"unverified"``).
        max_injection_score:
            Maximum allowed injection score 0.0–1.0 (default 0.7).

        Returns
        -------
        RetrieveResult
            Safe context text, verified chunks, and evidence_id.

        Raises
        ------
        RetrievalDeniedError
            If backend-api returns 403 (authorisation denied).
        ConnectionError
            If backend-api is unreachable after all retry attempts.
        """
        payload: dict[str, Any] = {
            "raw_results": raw_results,
            "email": email,
            "region": region,
            "max_tokens": max_tokens,
            "trust_threshold": trust_threshold,
            "max_injection_score": max_injection_score,
        }

        response = await self._transport.post("/api/v1/rag/secure-retrieve", json=payload)

        if response.status_code == 403:
            body = _safe_json(response)
            raise RetrievalDeniedError(
                "Retrieval denied by backend-api",
                denial_reason=body.get("reason") or body.get("detail"),
            )

        if response.status_code != 200:
            body = _safe_json(response)
            raise AetherGuardError(
                f"secure_retrieve failed with HTTP {response.status_code}: "
                f"{body.get('detail') or response.text}"
            )

        data = response.json()
        return RetrieveResult(
            text=data["text"],
            chunks=[_parse_safe_chunk(c) for c in data["chunks"]],
            total_retrieved=data["total_retrieved"],
            verified_count=data["verified_count"],
            blocked_count=data["blocked_count"],
            sanitized_count=data["sanitized_count"],
            token_count=data["token_count"],
            evidence_id=data["evidence_id"],
        )

    async def authorize(
        self,
        email: str, 
        region : str         
    ) -> AuthorizeResult:
        """
        Pre-check authorisation without performing retrieval.

        Parameters
        ----------
        user_id:
            User identifier.
        role:
            User's role.
        region:
            Data-residency region.

        Returns
        -------
        AuthorizeResult
            ``authorized`` flag, ``allowed_classifications``, and ``namespace``.

        Raises
        ------
        ConnectionError
            If backend-api is unreachable after all retry attempts.
        """
        payload: dict[str, Any] = {
            "email": email,
            "region" : region

         }

        response = await self._transport.post("/api/v1/rag/authorize", json=payload)

        if response.status_code == 403:
            data = response.json()
            raise AuthorizationError(
                "Authorization denied by backend-api",
                denial_reason=data.get("denial_reason"),
            )

        if response.status_code != 200:
            body = _safe_json(response)
            raise AetherGuardError(
                f"authorize failed with HTTP {response.status_code}: "
                f"{body.get('detail') or response.text}"
            )

        data = response.json()
        return AuthorizeResult(
            authorized=data["authorized"],
            namespace=data.get("namespace"),
            allowed_classifications=data.get("allowed_classifications", []),
            denial_reason=data.get("denial_reason"),
        )

    async def verify_chunk(self, chunk_id: str) -> VerifyResult:
        """
        On-demand verification of a single chunk's integrity.

        Parameters
        ----------
        chunk_id:
            UUID of the chunk to verify.

        Returns
        -------
        VerifyResult
            ``hash_valid``, ``signature_valid``, ``trust_level``, and ``exists``.

        Raises
        ------
        ConnectionError
            If backend-api is unreachable after all retry attempts.
        """
        response = await self._transport.get(f"/api/v1/rag/verify/{chunk_id}")

        if response.status_code not in (200, 404):
            body = _safe_json(response)
            raise AetherGuardError(
                f"verify_chunk failed with HTTP {response.status_code}: "
                f"{body.get('detail') or response.text}"
            )

        data = response.json()
        return VerifyResult(
            chunk_id=data["chunk_id"],
            hash_valid=data.get("hash_valid", False),
            signature_valid=data.get("signature_valid", False),
            trust_level=data.get("trust_level", "unverified"),
            exists=data.get("exists", False),
        )

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def close(self) -> None:
        """Close the underlying HTTP client and release connections."""
        await self._transport.aclose()

    async def __aenter__(self) -> AetherGuardRAG:
        return self

    async def __aexit__(self, *args: Any) -> None:
        await self.close()


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _safe_json(response: Any) -> dict[str, Any]:
    """Return parsed JSON body or empty dict if parsing fails."""
    try:
        return response.json()  # type: ignore[no-any-return]
    except Exception:
        return {}


def _parse_chunk_metadata(data: dict[str, Any]) -> ChunkMetadata:
    return ChunkMetadata(
        chunk_id=data["chunk_id"],
        chunk_hash=data["chunk_hash"],
        embedding_hash=data["embedding_hash"],
        signature=data["signature"],
        classification=data["classification"],
        trust_level=data["trust_level"],
        injection_score=float(data["injection_score"]),
        pii_detected=bool(data["pii_detected"]),
        secrets_detected=bool(data["secrets_detected"]),
        toxicity_score=float(data["toxicity_score"]),
        token_count=int(data["token_count"]),
        region=data["region"],
        signed_at=data["signed_at"],
    )


def _parse_safe_chunk(data: dict[str, Any]) -> SafeChunk:
    return SafeChunk(
        chunk_id=data["chunk_id"],
        content=data["content"],
        trust_level=data["trust_level"],
        classification=data["classification"],
        relevance_score=float(data["relevance_score"]),
        token_count=int(data["token_count"]),
    )
